packages:
  - src/packages/*
  - src/applications/*

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - extract-file-icon
  - fs-xattr
  - isolated-vm
  - macos-alias
  - node-window-manager
  - nx
  - puppeteer
  - sharp

nodeLinker: hoisted
